---
ID: "4061351a-8436-4ebf-b0f4-444348b15421"
Parent: "770ae618-40c0-4261-8d95-e6ffa93ee6fb"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/PointB-dev1/PointB-dev1/Settings/Shared Sites Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230314T152225Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\frueda@oshyn.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\frueda@oshyn.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8d5915f7-4e5e-4e67-b086-55c7e90ac10f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\frueda@oshyn.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230314T152225Z
