---
ID: "b1da99a7-734f-4faa-88c7-5a6eac28b80f"
Parent: "cb6cc3b3-e353-467e-8c35-473dd4b25f4d"
Template: "cb6cc3b3-e353-467e-8c35-473dd4b25f4d"
Path: "/sitecore/templates/Project/PointB-dev1/Partial Design Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {CB6CC3B3-E353-467E-8C35-473DD4B25F4D}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230314T152213Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\frueda@oshyn.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\frueda@oshyn.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cde99243-58e7-4f98-8786-b54e6d02bbe7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\frueda@oshyn.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230314T152216Z
